# Generated by Django 4.2.16 on 2024-12-01 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Максимальная длинна 150 символов",
                        max_length=150,
                        unique=True,
                        verbose_name="категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
        migrations.CreateModel(
            name="Paste",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Максимальная длинна 150 символов",
                        max_length=150,
                        verbose_name="заголовок",
                    ),
                ),
                (
                    "short_link",
                    models.CharField(
                        max_length=10,
                        unique=True,
                        verbose_name="короткая ссылка",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="опубликовано?"
                    ),
                ),
                (
                    "is_protected",
                    models.BooleanField(
                        default=False, verbose_name="Зашифровано?"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="создан"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="обновлён"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pastes",
                        related_query_name="paste",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="автор",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pastes",
                        related_query_name="paste",
                        to="paste.category",
                        verbose_name="категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "паста",
                "verbose_name_plural": "пасты",
            },
        ),
    ]
