# Generated by Django 4.2.16 on 2024-12-09 23:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Максимальная длинна 150 символов",
                        max_length=150,
                        unique=True,
                        verbose_name="категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
        migrations.CreateModel(
            name="ProtectedPaste",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Максимальная длинна 150 символов",
                        max_length=150,
                        verbose_name="заголовок",
                    ),
                ),
                (
                    "short_link",
                    models.CharField(
                        max_length=10,
                        unique=True,
                        verbose_name="короткая ссылка",
                    ),
                ),
                (
                    "expired_duration",
                    models.DurationField(
                        blank=True,
                        choices=[
                            (None, "Бессрочно"),
                            (datetime.timedelta(seconds=600), "10 минут"),
                            (datetime.timedelta(seconds=3600), "1 час"),
                            (datetime.timedelta(days=1), "1 день"),
                            (datetime.timedelta(days=5), "5 дней"),
                            (datetime.timedelta(days=10), "10 дней"),
                            (datetime.timedelta(days=30), "30 дней"),
                        ],
                        default=None,
                        null=True,
                        verbose_name="срок существования пасты",
                    ),
                ),
                (
                    "expired_date",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="дата уничтожения пасты",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="создана"
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        max_length=255, verbose_name="ключ шифрования"
                    ),
                ),
                ("salt", models.BinaryField(verbose_name="соль")),
                ("nonce", models.BinaryField(verbose_name="nonce")),
            ],
            options={
                "verbose_name": "зашифрованная паста",
                "verbose_name_plural": "зашифрованные пасты",
            },
        ),
        migrations.CreateModel(
            name="Paste",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Максимальная длинна 150 символов",
                        max_length=150,
                        verbose_name="заголовок",
                    ),
                ),
                (
                    "short_link",
                    models.CharField(
                        max_length=10,
                        unique=True,
                        verbose_name="короткая ссылка",
                    ),
                ),
                (
                    "expired_duration",
                    models.DurationField(
                        blank=True,
                        choices=[
                            (None, "Бессрочно"),
                            (datetime.timedelta(seconds=600), "10 минут"),
                            (datetime.timedelta(seconds=3600), "1 час"),
                            (datetime.timedelta(days=1), "1 день"),
                            (datetime.timedelta(days=5), "5 дней"),
                            (datetime.timedelta(days=10), "10 дней"),
                            (datetime.timedelta(days=30), "30 дней"),
                        ],
                        default=None,
                        null=True,
                        verbose_name="срок существования пасты",
                    ),
                ),
                (
                    "expired_date",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="дата уничтожения пасты",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="создана"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="опубликовано?"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="обновлён"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pastes",
                        related_query_name="paste",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="автор",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pastes",
                        related_query_name="paste",
                        to="paste.category",
                        verbose_name="категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "паста",
                "verbose_name_plural": "пасты",
            },
        ),
    ]
