# Generated by Django 4.2.16 on 2024-12-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paste", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paste",
            name="is_blocked",
            field=models.BooleanField(
                default=False, verbose_name="заблокировать"
            ),
        ),
        migrations.AlterField(
            model_name="paste",
            name="is_published",
            field=models.BooleanField(
                default=True, verbose_name="опубликовать"
            ),
        ),
    ]
