# Generated by Django 4.2.16 on 2024-11-30 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paste", "0002_category_alter_paste_author_paste_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paste",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="создан"
            ),
        ),
        migrations.AlterField(
            model_name="paste",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="обновлён"),
        ),
    ]
