# Generated by Django 4.2.16 on 2024-12-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paste", "0003_alter_paste_created_alter_paste_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="paste",
            name="is_protected",
            field=models.BooleanField(
                default=False, verbose_name="Зашифровать?"
            ),
        ),
    ]
