# Generated by Django 4.2.16 on 2024-12-01 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("paste", "0004_paste_is_protected"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paste",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pastes",
                related_query_name="paste",
                to="paste.category",
                verbose_name="категория",
            ),
        ),
    ]
