# Generated by Django 4.2.17 on 2024-12-18 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paste", "0004_alter_paste_language_alter_protectedpaste_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paste",
            name="expired_date",
        ),
        migrations.RemoveField(
            model_name="protectedpaste",
            name="expired_date",
        ),
    ]
