# Generated by Django 4.2.17 on 2024-12-18 22:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paste", "0005_remove_paste_expired_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="protectedpaste",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="обновлено"
            ),
        ),
        migrations.AlterField(
            model_name="paste",
            name="expired_duration",
            field=models.DurationField(
                blank=True,
                choices=[
                    (None, "Бессрочно"),
                    (datetime.timedelta(seconds=10), "10 секунд"),
                    (datetime.timedelta(seconds=600), "10 минут"),
                    (datetime.timedelta(seconds=3600), "1 час"),
                    (datetime.timedelta(days=1), "1 день"),
                    (datetime.timedelta(days=5), "5 дней"),
                    (datetime.timedelta(days=10), "10 дней"),
                    (datetime.timedelta(days=30), "30 дней"),
                ],
                default=None,
                null=True,
                verbose_name="срок существования пасты",
            ),
        ),
        migrations.AlterField(
            model_name="protectedpaste",
            name="expired_duration",
            field=models.DurationField(
                blank=True,
                choices=[
                    (None, "Бессрочно"),
                    (datetime.timedelta(seconds=10), "10 секунд"),
                    (datetime.timedelta(seconds=600), "10 минут"),
                    (datetime.timedelta(seconds=3600), "1 час"),
                    (datetime.timedelta(days=1), "1 день"),
                    (datetime.timedelta(days=5), "5 дней"),
                    (datetime.timedelta(days=10), "10 дней"),
                    (datetime.timedelta(days=30), "30 дней"),
                ],
                default=None,
                null=True,
                verbose_name="срок существования пасты",
            ),
        ),
    ]
