# Generated by Django 4.2.16 on 2024-12-19 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "paste",
            "0006_protectedpaste_updated_alter_paste_expired_duration_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pasteversion",
            name="short_link",
        ),
    ]
