# Generated by Django 4.2.16 on 2024-12-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Ваша аватарка",
                null=True,
                upload_to="media/profile_images/",
                verbose_name="Аватарка",
            ),
        ),
    ]
