# Generated by Django 4.2.17 on 2024-12-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_customuser_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="confirmation_token",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
